In [13]:
import pandas as pd

df = pd.read_csv("courses.csv")
display(df)

,Course_#,Name,Average_Semester_Grade,Pass_Rate,Professor,Professor_Rating,Format
0,201,Introduction to Information Science,89,NaN,Sauter,93,Online
1,126,Introduction to Programming for Information Sc...,85,NaN,Piety,70,Online
2,311,Information Organization,85,83,Byers,95,Online
3,311,Information Organization,87,90,Hawkins,97,Blended
4,314,Statistics for Information Science,85,92,Brown,90,In-Person
5,326,Object-Oriented Programming for Information Sc...,80,85,Dustin,89,Blended
6,327,Database Design and Modeling,88,96,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,123,Databases for All,93,NaN,Duffy,86,Online
9,152,"""Fake Checking"": Battling Misinformation and D...",88,NaN,Gorham-Oscilowski,92,Online
10,154,Apollo at 50,83,NaN,Oard,60,Online
11,155,Social Networking,88,NaN,Golbeck,70,Online
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,208A,Special Topics in Information Studies; HOW NAS...,86,NaN,Skakun,NaN,Online
14,208M,Special Topics in Information Studies; Academi...,95,NaN,TBA,NaN,TBA
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,309,Independent Study in Information Science,89,93,Chan,100,TBA
17,311,Information Organization,87,96,O'Grady,80,Online
18,314,Statistics for Information Science,75,92,Janzen,100,Online
19,326,Object-Oriented Programming for Information Sc...,77,91,Bills,100,Online
20,327,Database Design and Modeling,86,95,Duffy,100,Online
21,335,"Organizations, Management and Teamwork",80,91,Paletz,100,Online
22,346,"Technologies, Infrastructure and Architecture",88,96,Heidenblad,70,Blended
23,352,Information User Needs and Assessment,92,96,Gammons,100,Blended
24,354,Decision-Making for Information Science,85,96,Weaver,60,Blended
25,362,User-Centered Design,94,99,NaN,100,Online
26,366,"Privacy, Security and Ethics for Big Data",86,95,Vitak,100,Online
27,377,Dynamic Web Applications,77,85,Leitch,60,Online
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,408D,Special Topics in Information Science; Designi...,82,75,Choe,NaN,Online
30,408F,Special Topics in Information Science; Health ...,96,82,Sigalo,100,Online
31,408K,Special Topics in Information Science; Competi...,90,73,Shah,80,Online
32,408M,Special Topics in Information Science; Design ...,NaN,NaN,Conrad,NaN,NaN
33,408P,Special Topics in Information Science; Introdu...,NaN,NaN,TBA,NaN,NaN
34,408R,Special Topics in Information Science; Human-C...,NaN,NaN,Gao,NaN,NaN
35,414,Data Science Techniques,75,85,Ravindra-Bhat,93,Online
36,441,Information Ethics and Policy,93,85,Sauter,100,Online
37,443,Tools and Methods for Digital Curation,95,85,Marciano,NaN,Online
38,447,Data Sources and Manipulation,71,85,Ravindra-Bhat,93,Online
39,462,Introduction to Data Visualization,89,95,Golbeck,60,Online
40,464,Decision Making for Cybersecurity,91,98,Campbell,100,Online
41,466,"Technology, Culture, and Society",86,97,Piety,NaN,Online
42,467,Practical Hacking for Policy Makers,89,96,Harry,NaN,Online
43,490,Integrated Capstone for Information Science,97,100,Rainsford,100,Online
44,NaN,NaN,gpa,pass rate,NaN,prof rating,NaN
45,604,Introduction to Archives and Digital Curation,93,93,Marsh,NaN,Online
46,608J,Special Topics in Information Studies; Game De...,94,97,Elmqvist,NaN,Online
47,612,Information Policy,94,94,Jaeger,NaN,Online
48,614,Literacy and Inclusion,94,98,Adle,NaN,Online
49,616,Open Source Intelligence,94,86,Francis,NaN,Online
50,622,Information and Universal Usability,94,93,Hill,100,Online

In [14]:
def sort_courses():
    
    print("Please choose to sort by one of the following:")
    key_word = input("Course Number, Name, Avg. Semester Grade, Pass Rate, Professor, Professor Rating, or Format")
    
    if key_word == "Course Number":
        co_num_df = df.sort_values(by='Course_#')
        display(co_num_df)
    elif key_word == "Name":
        name_df = df.sort_values(by='Name')
        display(name_df)
    elif key_word == "Avg. Semester Grade":
        grade_df = df.sort_values(by='Average_Semester_Grade')
        display(grade_df)
    elif key_word == "Pass Rate":
        pass_df = df.sort_values(by='Pass_Rate')
        display(pass_df)
    elif key_word == "Professor":
        prof_df = df.sort_values(by='Professor')
        display(prof_df)
    elif key_word == "Professor Rating":
        prof_rate_df = df.sort_values(by='Professor_Rating')
        display(prof_rate_df)
    elif key_word == "Format":
        form_df = df.sort_values(by='Format')
        display(form_df)

In [15]:
def search_courses():
    
    print("Please choose to search one of the following:")
    key_word = input("Course Number, Name, Avg. Semester Grade, Pass Rate, Professor, or Format")
    search_term = input("Now, enter your search criteria:")
    
    if key_word == "Course Number":
        co_num_df = df[df['Course_#'] == int(search_term)]
        display(co_num_df)
    elif key_word == "Name":
        name_df = df[df['Name'] == search_term]
        display(name_df)
    elif key_word == "Avg. Semester Grade":
        grade_df = df[df['Average_Semester_Grade'] == int(search_term)]
        display(grade_df)
    elif key_word == "Pass Rate":
        pass_df = df[df['Pass_Rate'] == int(search_term)]
        display(pass_df)
    elif key_word == "Professor":
        prof_df = df[df['Professor'] == search_term]
        display(prof_df)
    elif key_word == "Format":
        form_df = df[df['Format'] == search_term]
        display(form_df)

In [16]:
def save_courses(save_option):
    
    saving = True
    
    if save_option == "Yes":
        while saving == True:
            num = input("Enter the leftmost value of the course you would like to save.")
            saved_courses.append(int(num))
            save_option = input("Continue? Yes or No.")
            if save_option == "No":
                saving = False

In [17]:
def function_select(option):
    
    running = True
    not_First = True
    
    while running == True:
        
        if not_First == False:
            option = input("Would you like to sort or search?")
            
        if option == "Sort":
            sort_courses()
        elif option == "Search":
            search_courses()
        else:
            print("Invalid Option")
            
        save_option = input("Would you like to save a course? Yes or No.")
        save_courses(save_option)
            
        cont_running = input("Would you like to continue running the program? Yes or No.")
        if cont_running == "No":
            running = False
            for i in saved_courses:
                print(f"{df.iloc[i]}\n----------------------\n")
                
        not_First = False

In [18]:
global saved_courses
saved_courses = []

option = input("Would you like to sort or search?")
function_select(option)

Would you like to sort or search? Sort

Please choose to sort by one of the following:

Course Number, Name, Avg. Semester Grade, Pass Rate, Professor, Professor Rating, or Format Name

,Course_#,Name,Average_Semester_Grade,Pass_Rate,Professor,Professor_Rating,Format
9,152,"""Fake Checking"": Battling Misinformation and D...",88,NaN,Gorham-Oscilowski,92,Online
10,154,Apollo at 50,83,NaN,Oard,60,Online
35,414,Data Science Techniques,75,85,Ravindra-Bhat,93,Online
38,447,Data Sources and Manipulation,71,85,Ravindra-Bhat,93,Online
20,327,Database Design and Modeling,86,95,Duffy,100,Online
6,327,Database Design and Modeling,88,96,NaN,NaN,NaN
8,123,Databases for All,93,NaN,Duffy,86,Online
40,464,Decision Making for Cybersecurity,91,98,Campbell,100,Online
24,354,Decision-Making for Information Science,85,96,Weaver,60,Blended
27,377,Dynamic Web Applications,77,85,Leitch,60,Online
16,309,Independent Study in Information Science,89,93,Chan,100,TBA
36,441,Information Ethics and Policy,93,85,Sauter,100,Online
2,311,Information Organization,85,83,Byers,95,Online
3,311,Information Organization,87,90,Hawkins,97,Blended
17,311,Information Organization,87,96,O'Grady,80,Online
47,612,Information Policy,94,94,Jaeger,NaN,Online
23,352,Information User Needs and Assessment,92,96,Gammons,100,Blended
50,622,Information and Universal Usability,94,93,Hill,100,Online
43,490,Integrated Capstone for Information Science,97,100,Rainsford,100,Online
45,604,Introduction to Archives and Digital Curation,93,93,Marsh,NaN,Online
39,462,Introduction to Data Visualization,89,95,Golbeck,60,Online
0,201,Introduction to Information Science,89,NaN,Sauter,93,Online
1,126,Introduction to Programming for Information Sc...,85,NaN,Piety,70,Online
48,614,Literacy and Inclusion,94,98,Adle,NaN,Online
5,326,Object-Oriented Programming for Information Sc...,80,85,Dustin,89,Blended
19,326,Object-Oriented Programming for Information Sc...,77,91,Bills,100,Online
49,616,Open Source Intelligence,94,86,Francis,NaN,Online
21,335,"Organizations, Management and Teamwork",80,91,Paletz,100,Online
42,467,Practical Hacking for Policy Makers,89,96,Harry,NaN,Online
26,366,"Privacy, Security and Ethics for Big Data",86,95,Vitak,100,Online
11,155,Social Networking,88,NaN,Golbeck,70,Online
31,408K,Special Topics in Information Science; Competi...,90,73,Shah,80,Online
32,408M,Special Topics in Information Science; Design ...,NaN,NaN,Conrad,NaN,NaN
29,408D,Special Topics in Information Science; Designi...,82,75,Choe,NaN,Online
30,408F,Special Topics in Information Science; Health ...,96,82,Sigalo,100,Online
34,408R,Special Topics in Information Science; Human-C...,NaN,NaN,Gao,NaN,NaN
33,408P,Special Topics in Information Science; Introdu...,NaN,NaN,TBA,NaN,NaN
14,208M,Special Topics in Information Studies; Academi...,95,NaN,TBA,NaN,TBA
46,608J,Special Topics in Information Studies; Game De...,94,97,Elmqvist,NaN,Online
13,208A,Special Topics in Information Studies; HOW NAS...,86,NaN,Skakun,NaN,Online
4,314,Statistics for Information Science,85,92,Brown,90,In-Person
18,314,Statistics for Information Science,75,92,Janzen,100,Online
22,346,"Technologies, Infrastructure and Architecture",88,96,Heidenblad,70,Blended
41,466,"Technology, Culture, and Society",86,97,Piety,NaN,Online
37,443,Tools and Methods for Digital Curation,95,85,Marciano,NaN,Online
25,362,User-Centered Design,94,99,NaN,100,Online
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,gpa,pass rate,NaN,prof rating,NaN

Would you like to save a course? Yes or No. Yes
Enter the leftmost value of the course you would like to save. 2
Continue? Yes or No. Yes
Enter the leftmost value of the course you would like to save. 3
Continue? Yes or No. No
Would you like to continue running the program? Yes or No. Yes
Would you like to sort or search? Search

Please choose to search one of the following:

Course Number, Name, Avg. Semester Grade, Pass Rate, Professor, or Format Format
Now, enter your search criteria: Blended

,Course_#,Name,Average_Semester_Grade,Pass_Rate,Professor,Professor_Rating,Format
3,311,Information Organization,87,90,Hawkins,97,Blended
5,326,Object-Oriented Programming for Information Sc...,80,85,Dustin,89,Blended
22,346,"Technologies, Infrastructure and Architecture",88,96,Heidenblad,70,Blended
23,352,Information User Needs and Assessment,92,96,Gammons,100,Blended
24,354,Decision-Making for Information Science,85,96,Weaver,60,Blended

Would you like to save a course? Yes or No. Yes
Enter the leftmost value of the course you would like to save. 5
Continue? Yes or No. No
Would you like to continue running the program? Yes or No. No

Course_#                                       311
Name                      Information Organization
Average_Semester_Grade                          85
Pass_Rate                                       83
Professor                                    Byers
Professor_Rating                                95
Format                                      Online
Name: 2, dtype: object
----------------------

Course_#                                       311
Name                      Information Organization
Average_Semester_Grade                          87
Pass_Rate                                       90
Professor                                  Hawkins
Professor_Rating                                97
Format                                     Blended
Name: 3, dtype: object
----------------------

Course_#                                                                326
Name                      Object-Oriented Programming for Information Sc...
Average_Semester_Grade                                                   80
Pass_Rate                                                                85
Professor                                                            Dustin
Professor_Rating                                                         89
Format                                                              Blended
Name: 5, dtype: object
----------------------